#! /bin/bash

nerror=0
nok=0
notapp=0
fail=


echo
echo
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Test session ended at $(date)"

dirs=$(
    for file in */Makefile
    do
      echo ${file%Makefile}
    done
)

for dir in $dirs
do
  file=${dir}report.txt
  fullname="$file"
  if grep -q NOT_APPLIABLE $file ; then
    ((notapp++))
    echo + test $dir NOT APPLIABLE
    echo + check file $fullname for more information
  elif grep -q FAILURE $file ; then
    ((nerror++))
    echo + ERROR in test $dir
    echo + check file $fullname for more information
  else
    ((nok++))
  fi
done

echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+ Final report:"
echo "+ $((nok+nerror)) tests performed, $notapp tests not appliable"
echo "+ $nerror errors found"
if ((nerror==0)) ; then
echo "+ Well done!!"
else
echo "+ Find the bug!"
echo "+ To replace references, go to the test directory and"
echo "+ type 'make reset'"
  exit 1
fi
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
echo



