#! /bin/bash

{

date
echo "Running regtest in $(pwd)"
export BARNABA=../../../baRNAba
export DATA=../../../examples/DATA

rm -fr tmp
mkdir tmp
cd tmp

cp ../* .

./test.sh >out 2>err

echo "Done."
#echo "Here is the output file:"
#cat out
echo "Here is the error file:"
cat err


if ls *.reference > /dev/null
then
for file in *.reference ;
do
  new="${file%.reference}"
  if test -f "$new" ; then
    out="$(diff "$file" "$new")"
  test -n "$out" && {
      echo FAILURE
      echo "Diff for ${file%.reference}:"
      diff "${file}" "$new"
    }
  else
    echo FAILURE
    echo FILE $new does not exist
  fi
done
else
    echo WARNING
    echo no file has been checked
fi

} | tee report.txt
